API 0
POST http://localhost:3000/login/
Content-Type: application/json

{
  "username": "christopher_phillips",
  "password": "christy@123"
}


API1
GET http://localhost:3000/states/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzA2MDI2NjU5fQ.6VDgaWTTKrmkVYtiWtUFiY4E1ZmgMa8bRVJlHdlTwIc


API2
GET http://localhost:3000/states/3/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzA2MDI2NjU5fQ.6VDgaWTTKrmkVYtiWtUFiY4E1ZmgMa8bRVJlHdlTwIc


API3
POST http://localhost:3000/districts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzA2MDI2NjU5fQ.6VDgaWTTKrmkVYtiWtUFiY4E1ZmgMa8bRVJlHdlTwIc
Content-Type: application/json

{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}

API4
GET http://localhost:3000/districts/4/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzA2MDI2NjU5fQ.6VDgaWTTKrmkVYtiWtUFiY4E1ZmgMa8bRVJlHdlTwIc


API5
DELETE http://localhost:3000/districts/766/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzA2MDI2NjU5fQ.6VDgaWTTKrmkVYtiWtUFiY4E1ZmgMa8bRVJlHdlTwIc



API6
PUT http://localhost:3000/districts/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzA2MDI2NjU5fQ.6VDgaWTTKrmkVYtiWtUFiY4E1ZmgMa8bRVJlHdlTwIc
Content-Type: application/json

{
  "districtName": "Nadia",
  "stateId": 3,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}


API7
GET http://localhost:3000/states/10/stats/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzA2MDI2NjU5fQ.6VDgaWTTKrmkVYtiWtUFiY4E1ZmgMa8bRVJlHdlTwIc


API8
GET http://localhost:3000/districts/6/details/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzA2MDI2NjU5fQ.6VDgaWTTKrmkVYtiWtUFiY4E1ZmgMa8bRVJlHdlTwIc

